# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\x07\n\x05\x45mpty\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\x0b\x41PIResponse\x12\x17\n\x0fresponseMessage\x18\x01 \x01(\t\x12\x14\n\x0cresponseCode\x18\x02 \x01(\x05\x32L\n\x04user\x12$\n\x05login\x12\r.LoginRequest\x1a\x0c.APIResponse\x12\x1e\n\x06logout\x12\x06.Empty\x1a\x0c.APIResponseB\r\n\x0b\x63om.exampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.example'
  _globals['_EMPTY']._serialized_start=14
  _globals['_EMPTY']._serialized_end=21
  _globals['_LOGINREQUEST']._serialized_start=23
  _globals['_LOGINREQUEST']._serialized_end=73
  _globals['_APIRESPONSE']._serialized_start=75
  _globals['_APIRESPONSE']._serialized_end=135
  _globals['_USER']._serialized_start=137
  _globals['_USER']._serialized_end=213
# @@protoc_insertion_point(module_scope)
